[programs.localnet]
mycalculatordapp = "65Hmk46LP743bborgmZHVucHFoLn1aEE2yXiitGwi5QL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chsk_kishore/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
